# Set up a simple sudoers file
---
- include: install.yml

- name: Copying, Verifying and placing sudo file
  template: >
    src="{{ sudo_sudoers_template | mandatory }}"
    dest=/etc/sudoers
    owner="{{ sudo_sudoers_file_owner | omit }}"
    group="{{ sudo_sudoers_file_group | omit }}"
    mode="{{ sudo_sudoers_file_mode | omit }}"
    validate='visudo -cf %s'
...
